### ISSUE TITLE
Auto-generate buttons are there even if no generateTitle/generateDescription/etc configured

### ISSUE THREAD

**Issue by zanami** [payloadcms/plugin-seo#34]
Clicking on 'Auto-generate' does nothing in this case. Just a minor UI issue I guess.

**Comment by dragos199993** [comment]
Hey 👋 Is it supposed to be something like this? 
![image](https://user-images.githubusercontent.com/22987936/217529738-bed34b89-2ae8-4723-947b-a39039fd76c1.png)

Did a fix on MetaTitle, but wanted to be sure this is the correct approach. If I get the green light from one of the maintainers I can open a PR.

The solution will be to check in each component: MetaTitle, MetaDescription and MetaImage if we have value on the field.
This can be achieved by using a useState and an useEffect that updates this value based on the generate* function response:

```const [fieldVisible, setFieldVisible] = useState(false);```
```const getFieldVisible = useCallback(async () => {
    const { generateTitle } = pluginConfig;

    if (typeof generateTitle === "function") {
      setFieldVisible(!!(await generateTitle({ doc: { ...fields }, locale })));
    }
  }, []);
```

After that we only add the "if statement" in JSX to disable the label:
```
{fieldVisible && (
            <>
              &nbsp; &mdash; &nbsp;
              <button
                onClick={regenerateTitle}
                type="button"
                style={{
                  padding: 0,
                  background: "none",
                  border: "none",
                  backgroundColor: "transparent",
                  cursor: "pointer",
                  textDecoration: "underline",
                  color: "currentcolor",
                }}
              >
                Auto-generate
              </button>
            </>
          )}
```

However since this logic will be repeated, maybe it can be extracted in a small custom hook?

**Comment by jacobsfletch** [comment]
@dragos199993 that's pretty much it but to make this much simpler just add that condition directly to the JSX and don't use state, like this:

```js
{typeof generateTitle === 'function' && (
  <>
    &nbsp; &mdash; &nbsp;
    <button
      onClick={regenerateTitle}
      type="button"
      style={{
        padding: 0,
        background: "none",
        border: "none",
        backgroundColor: "transparent",
        cursor: "pointer",
        textDecoration: "underline",
        color: "currentcolor",
      }}
    >
      Auto-generate
    </button>
  </>
)}
```

I'd happily merge a PR if you wanted to give this a shot!

**Comment by edtorba** [comment]
Am on 1.0.10 and it's still showing 👀
My config:

```js
seo({
    collections: [
      'pages',
    ],
    uploadsCollection: 'media',
  },),
```

<img width="462" alt="Screenshot 2023-05-13 at 11 54 17" src="https://github.com/payloadcms/plugin-seo/assets/2422019/b5fbf6e5-a293-40c5-acbb-a9bbd6fbf56f">

**Comment by jacobsfletch** [comment]
Hey @edtorba looks like this PR was merged in but not released. I'll cut a new release for this as soon as possible.
